import Head from "next/head"
import style from '../styles/layout.module.css'
import Menu from "./menu"
import ShoppingCart from "./shoppingCart"

export default function Layout ({children, title}) {
    return(
        <div>
        <Head>
        <title>Globe City{title ? ` |  ${title}`: ""} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Menu></Menu>

            <div className={style.container} >
                {children}
            </div>
            <ShoppingCart />

        <footer className={style.footer}>
            <div>
                Redes sociales: 
            </div>
            <div>
                Contacto: 
            </div>
        </footer>
        </div>




    )
}